spring:
  application:
    name: pos-counter
server:
  port: 8685
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8666/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}